### ISSUE TITLE
bug: gallery sync doesn't work on android

### ISSUE THREAD

**Issue by stwgabriel** [internxt/drive-mobile#91]
App version: 1.5.10
Android version: 11

my steps:

- open the app  
  - photos tab 
   - start syncing my photos 
   - top left message: preparing > syncing > syncing 0 of 54 > pending synchronization
   - bottom popup appears: 

![signal-2022-04-27-143631](https://user-images.githubusercontent.com/61845917/165586381-080f3972-9ce1-4fdc-9ed6-b573661a833c.png)

**Comment by Juasmis** [comment]
Same here, happening in all versions

**Comment by PixoDev** [comment]
Hey we released an entire rebuild of the Internxt Photos sync system (1.5.14), can you please update your app and let me know if it's working now?

You can find the PR of the rebuild here if you are interested:
https://github.com/internxt/drive-mobile/pull/101

Thanks!

**Comment by Juasmis** [comment]
Hi, first of all, congratulations to the team the syncing does not break anymore! 🎉

Now that it works when you have time it would be good to add some options:
- Selective sync, being able to select which folder to sync
- When to sync, only when plugged, use mobile data, etc
- Include a timeline scroll (years popup when selecting the scroll)
- Have the ability to tag pictures, add to favourites 
- Notifications for the syncing progress

All of these would make it worh to use Internxt just for the photos backup service apart from all the other capabilities.

Good work!

**Comment by PixoDev** [comment]
Hey! happy to see that everything is working smoothly!!

We are not tracking features requests over here, we only check for bugs/issues with our products actually.

We are discussing about using a public roadmap or something similar for this kind of requests, I'm going to share your feedback with the product team this time, but in the feature we are probably going to request the users to use another channel to this kind of things.

Closing the issue since this is already resolved.

Have a nice day!

**Comment by stwgabriel** [comment]
after found this problem I decide no to use internxt anymore but now it works perfectly!

thx for the solution sorry for the delay.

Happy hacking!
